name: Build and Deploy Lists

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Create Shadow JAR
        run: gradle shadowJar
      - name: Create Lists
        run: |
          mkdir -p dist
          cd dist
          java -cp ../build/libs/kickmail-all.jar io.noticeable.kickmail.AggregateLists
          ls -lh
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages publish ./ --project-name kickmail
          workingDirectory: dist