name: Build and Deploy Lists

on:
  push:
    branches: [ "main" ]
    paths:
      - "lists/**"
      - "src/main/java/**"
      - ".github/workflows/build-deploy-lists.yaml"
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
      - name: Create Shadow JAR
        run: gradle shadowJar
      - name: Create Lists
        run: |
          java -cp build/libs/kickmail-all.jar io.noticeable.kickmail.AggregateLists lists dist/denylist.txt
          ls -lh dist
      - name: Publish
        uses: cloudflare/wrangler-action@v3.15.0
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages deploy ./ --project-name kickmail
          workingDirectory: dist