name: Keepalive

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  keep-repo-active:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Commit keepalive timestamp
        run: |
          date -u +"%Y-%m-%dT%H:%M:%SZ" > .keepalive
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .keepalive
          git commit -m "ci(keepalive): prevent scheduled workflows from being disabled" || exit 0
          git push